version: '3.8'

services:
  recycling-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./recycling_app.db:/app/recycling_app.db
    environment:
      - DATABASE_URL=sqlite:///./recycling_app.db
      - PYTHONPATH=/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/recycling/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
